var fs = require('fs/promises');
var path = require('path');

var ASSETS = path.resolve(__dirname, '../src/assets');
var CLASSNAME = 'svgicon';
var OUT = 'SVGIcons.jsx';

var TEMPLATE = `
// DO NOT EDIT
// AUTO GENERATED BY scripts/SVGIcons.js
`;
var REG_ATTR = /\s(\w+(-\w+)+)="/g;

async function main() {
  var files = await fs.readdir(ASSETS);
  var svgIcons = files.filter(v => v.endsWith('.svg'));
  var out = await fs.open(path.join(ASSETS, OUT), 'w');
  await out.write(TEMPLATE);
  for (var fileName of svgIcons) {
    var fileNameExt = fileName.slice(0, -4);
    var name = camelCase(fileNameExt);
    var svg = await fs.readFile(path.join(ASSETS, fileName), 'utf-8');
    svg = svg.trim();
    svg = svg.replace(REG_ATTR, (s, s1) => ` ${camelCase(s1, 0)}="`);
    svg = `<svg className="${CLASSNAME} ${fileNameExt}"${svg.substring(4)}`;
    await out.write(`
export function ${name}() {
  return ${svg};
}
`);
  }
  await out.close();
  console.log('Generate svg icons to %o', `src/assets/${OUT}`);
}
main();

/**
 * 首字母大写
 * @param {string} s 
 * @param {number} idx 取消某个单词的首字母大写
 */
function camelCase(s, idx = -1) {
  return s.split('-').map((v, i) => i==idx ? v : v[0].toUpperCase()+v.substring(1)).join('');
}
